apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
- https://github.com/redhat-cop/gitops-catalog/advanced-cluster-security-operator/aggregate/minimal?ref=9f00dfed1214a628c6419ac3517417bd05f4da82
